// Generated by gencpp from file head_pkg/Automation.msg
// DO NOT EDIT!


#ifndef HEAD_PKG_MESSAGE_AUTOMATION_H
#define HEAD_PKG_MESSAGE_AUTOMATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace head_pkg
{
template <class ContainerAllocator>
struct Automation_
{
  typedef Automation_<ContainerAllocator> Type;

  Automation_()
    : header()
    , relay1(false)
    , relay2(false)
    , relay3(false)  {
    }
  Automation_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , relay1(false)
    , relay2(false)
    , relay3(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _relay1_type;
  _relay1_type relay1;

   typedef uint8_t _relay2_type;
  _relay2_type relay2;

   typedef uint8_t _relay3_type;
  _relay3_type relay3;





  typedef boost::shared_ptr< ::head_pkg::Automation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::head_pkg::Automation_<ContainerAllocator> const> ConstPtr;

}; // struct Automation_

typedef ::head_pkg::Automation_<std::allocator<void> > Automation;

typedef boost::shared_ptr< ::head_pkg::Automation > AutomationPtr;
typedef boost::shared_ptr< ::head_pkg::Automation const> AutomationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::head_pkg::Automation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::head_pkg::Automation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace head_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'head_pkg': ['/home/pi/Desktop/anamatronic/Ros/Anama_Catkin_ws/src/head_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::head_pkg::Automation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::head_pkg::Automation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::head_pkg::Automation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::head_pkg::Automation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::head_pkg::Automation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::head_pkg::Automation_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::head_pkg::Automation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb789613f23439dcb13bc2641016e45e";
  }

  static const char* value(const ::head_pkg::Automation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb789613f23439dcULL;
  static const uint64_t static_value2 = 0xb13bc2641016e45eULL;
};

template<class ContainerAllocator>
struct DataType< ::head_pkg::Automation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "head_pkg/Automation";
  }

  static const char* value(const ::head_pkg::Automation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::head_pkg::Automation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool relay1\n\
bool relay2\n\
bool relay3\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::head_pkg::Automation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::head_pkg::Automation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.relay1);
      stream.next(m.relay2);
      stream.next(m.relay3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Automation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::head_pkg::Automation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::head_pkg::Automation_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "relay1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relay1);
    s << indent << "relay2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relay2);
    s << indent << "relay3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relay3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEAD_PKG_MESSAGE_AUTOMATION_H
