// Generated by gencpp from file head_pkg/Head.msg
// DO NOT EDIT!


#ifndef HEAD_PKG_MESSAGE_HEAD_H
#define HEAD_PKG_MESSAGE_HEAD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace head_pkg
{
template <class ContainerAllocator>
struct Head_
{
  typedef Head_<ContainerAllocator> Type;

  Head_()
    : header()
    , eyesX(0)
    , eyesY(0)
    , jawX(0)
    , jawY(0)
    , eyeSkwint(0)
    , jawZ(0)
    , expression(0)
    , blink(false)
    , supprise(false)
    , rightNose(false)
    , leftNose(false)  {
    }
  Head_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , eyesX(0)
    , eyesY(0)
    , jawX(0)
    , jawY(0)
    , eyeSkwint(0)
    , jawZ(0)
    , expression(0)
    , blink(false)
    , supprise(false)
    , rightNose(false)
    , leftNose(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _eyesX_type;
  _eyesX_type eyesX;

   typedef int16_t _eyesY_type;
  _eyesY_type eyesY;

   typedef int16_t _jawX_type;
  _jawX_type jawX;

   typedef int16_t _jawY_type;
  _jawY_type jawY;

   typedef int16_t _eyeSkwint_type;
  _eyeSkwint_type eyeSkwint;

   typedef int16_t _jawZ_type;
  _jawZ_type jawZ;

   typedef int16_t _expression_type;
  _expression_type expression;

   typedef uint8_t _blink_type;
  _blink_type blink;

   typedef uint8_t _supprise_type;
  _supprise_type supprise;

   typedef uint8_t _rightNose_type;
  _rightNose_type rightNose;

   typedef uint8_t _leftNose_type;
  _leftNose_type leftNose;





  typedef boost::shared_ptr< ::head_pkg::Head_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::head_pkg::Head_<ContainerAllocator> const> ConstPtr;

}; // struct Head_

typedef ::head_pkg::Head_<std::allocator<void> > Head;

typedef boost::shared_ptr< ::head_pkg::Head > HeadPtr;
typedef boost::shared_ptr< ::head_pkg::Head const> HeadConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::head_pkg::Head_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::head_pkg::Head_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace head_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'head_pkg': ['/home/pi/Desktop/anamatronic/Ros/Anama_Catkin_ws/src/head_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::head_pkg::Head_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::head_pkg::Head_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::head_pkg::Head_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::head_pkg::Head_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::head_pkg::Head_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::head_pkg::Head_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::head_pkg::Head_<ContainerAllocator> >
{
  static const char* value()
  {
    return "802348f5a2f1e8dfd50efdc8d6faf838";
  }

  static const char* value(const ::head_pkg::Head_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x802348f5a2f1e8dfULL;
  static const uint64_t static_value2 = 0xd50efdc8d6faf838ULL;
};

template<class ContainerAllocator>
struct DataType< ::head_pkg::Head_<ContainerAllocator> >
{
  static const char* value()
  {
    return "head_pkg/Head";
  }

  static const char* value(const ::head_pkg::Head_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::head_pkg::Head_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int16 eyesX\n\
int16 eyesY\n\
int16 jawX\n\
int16 jawY\n\
int16 eyeSkwint\n\
int16 jawZ\n\
int16 expression\n\
bool blink\n\
bool supprise\n\
bool rightNose\n\
bool leftNose\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::head_pkg::Head_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::head_pkg::Head_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.eyesX);
      stream.next(m.eyesY);
      stream.next(m.jawX);
      stream.next(m.jawY);
      stream.next(m.eyeSkwint);
      stream.next(m.jawZ);
      stream.next(m.expression);
      stream.next(m.blink);
      stream.next(m.supprise);
      stream.next(m.rightNose);
      stream.next(m.leftNose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Head_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::head_pkg::Head_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::head_pkg::Head_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "eyesX: ";
    Printer<int16_t>::stream(s, indent + "  ", v.eyesX);
    s << indent << "eyesY: ";
    Printer<int16_t>::stream(s, indent + "  ", v.eyesY);
    s << indent << "jawX: ";
    Printer<int16_t>::stream(s, indent + "  ", v.jawX);
    s << indent << "jawY: ";
    Printer<int16_t>::stream(s, indent + "  ", v.jawY);
    s << indent << "eyeSkwint: ";
    Printer<int16_t>::stream(s, indent + "  ", v.eyeSkwint);
    s << indent << "jawZ: ";
    Printer<int16_t>::stream(s, indent + "  ", v.jawZ);
    s << indent << "expression: ";
    Printer<int16_t>::stream(s, indent + "  ", v.expression);
    s << indent << "blink: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blink);
    s << indent << "supprise: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.supprise);
    s << indent << "rightNose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rightNose);
    s << indent << "leftNose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.leftNose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEAD_PKG_MESSAGE_HEAD_H
