// Generated by gencpp from file head_pkg/Neck.msg
// DO NOT EDIT!


#ifndef HEAD_PKG_MESSAGE_NECK_H
#define HEAD_PKG_MESSAGE_NECK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace head_pkg
{
template <class ContainerAllocator>
struct Neck_
{
  typedef Neck_<ContainerAllocator> Type;

  Neck_()
    : header()
    , NeckTurnPos(0)
    , HeadPitch(0)
    , HeadRoll(0)
    , SensPitch(0.0)
    , SensRoll(0.0)
    , ToungeExpression(0)  {
    }
  Neck_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , NeckTurnPos(0)
    , HeadPitch(0)
    , HeadRoll(0)
    , SensPitch(0.0)
    , SensRoll(0.0)
    , ToungeExpression(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _NeckTurnPos_type;
  _NeckTurnPos_type NeckTurnPos;

   typedef int16_t _HeadPitch_type;
  _HeadPitch_type HeadPitch;

   typedef int16_t _HeadRoll_type;
  _HeadRoll_type HeadRoll;

   typedef float _SensPitch_type;
  _SensPitch_type SensPitch;

   typedef float _SensRoll_type;
  _SensRoll_type SensRoll;

   typedef int16_t _ToungeExpression_type;
  _ToungeExpression_type ToungeExpression;





  typedef boost::shared_ptr< ::head_pkg::Neck_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::head_pkg::Neck_<ContainerAllocator> const> ConstPtr;

}; // struct Neck_

typedef ::head_pkg::Neck_<std::allocator<void> > Neck;

typedef boost::shared_ptr< ::head_pkg::Neck > NeckPtr;
typedef boost::shared_ptr< ::head_pkg::Neck const> NeckConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::head_pkg::Neck_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::head_pkg::Neck_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace head_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'head_pkg': ['/home/pi/Desktop/anamatronic/Ros/Anama_Catkin_ws/src/head_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::head_pkg::Neck_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::head_pkg::Neck_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::head_pkg::Neck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::head_pkg::Neck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::head_pkg::Neck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::head_pkg::Neck_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::head_pkg::Neck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee86276cb042e4ad198a659440dd1e51";
  }

  static const char* value(const ::head_pkg::Neck_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee86276cb042e4adULL;
  static const uint64_t static_value2 = 0x198a659440dd1e51ULL;
};

template<class ContainerAllocator>
struct DataType< ::head_pkg::Neck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "head_pkg/Neck";
  }

  static const char* value(const ::head_pkg::Neck_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::head_pkg::Neck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int16 NeckTurnPos\n\
int16 HeadPitch\n\
int16 HeadRoll\n\
float32 SensPitch\n\
float32 SensRoll\n\
int16 ToungeExpression\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::head_pkg::Neck_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::head_pkg::Neck_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.NeckTurnPos);
      stream.next(m.HeadPitch);
      stream.next(m.HeadRoll);
      stream.next(m.SensPitch);
      stream.next(m.SensRoll);
      stream.next(m.ToungeExpression);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Neck_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::head_pkg::Neck_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::head_pkg::Neck_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "NeckTurnPos: ";
    Printer<int16_t>::stream(s, indent + "  ", v.NeckTurnPos);
    s << indent << "HeadPitch: ";
    Printer<int16_t>::stream(s, indent + "  ", v.HeadPitch);
    s << indent << "HeadRoll: ";
    Printer<int16_t>::stream(s, indent + "  ", v.HeadRoll);
    s << indent << "SensPitch: ";
    Printer<float>::stream(s, indent + "  ", v.SensPitch);
    s << indent << "SensRoll: ";
    Printer<float>::stream(s, indent + "  ", v.SensRoll);
    s << indent << "ToungeExpression: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ToungeExpression);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEAD_PKG_MESSAGE_NECK_H
